### PR TITLE
Add salsa20

### PR DESCRIPTION
**Pull request by catwell**
I am working towards the first item of "In the future..." from the README, namely the implementation of box and secretbox. This is the first step: salsa20.

### CODE REVIEW

**Comment by catwell** [comment]
(If you prefer you can wait until I finish everything to review / merge all at once.)

**Comment by philanc** [comment]
Bonjour Pierre,

This is great!  And I was going to ask if you would have a HSalsa20 (for a complete key exchange compatible with NaCl) and just noticed you added it. Yay!  

I will review all this ASAP.

**Comment by philanc** [comment]
Hi Pierre, Sorry for the silly question but I have very limited experience with github :-)

How do I merge your more recent commits (HSalsa20)?  I can of course do it manually, but what is the normal / correct / polite way to do it?  should I wait for a new pull request from you?

Thanks for the nice salsa20 and for your help

**Comment by catwell** [comment]
@philanc I had added hsalsa20 in #6 which implements the box API :)

**Pull request merged**
